### ISSUE TITLE
Using D3/D4 is not a good idea

### ISSUE THREAD

**Issue by tobox** [b4ckspace/esp8266-co2monitor#1]
I followed you instructions, but my wemos would not boot when connect to the co2 monitor. After pressing the reset button, it worked. 

According to https://www.forward.com.au/pfod/ESP8266/GPIOpins/index.html it is not a good idea to use GPIO0 and GPIO2 as inputs (D3/D4 on Wemos D1 mini).

So I switched to D1 and D2, and now everything works flawessly.

**Comment by schinken** [comment]
Ha! Big thanks for that! I wondered why I have this issue, but haven't investigated further. I'm going to rewrite my sensors tomorrow and update the documentation and code.

Thanks for your bug report!

**Comment by schinken** [comment]
Fixed! And thx again!
