### ISSUE TITLE
ESPEASY 

### ISSUE THREAD

**Issue by fireball79** [b4ckspace/esp8266-co2monitor#12]
Hi, kann man den Code auch irgendwie in espeasy reinbekommen?
Einige der neueren Geräte braucht man nicht mehr zu entschlüsseln, was ist hier notwendig, falls man so ein Gerät hat? Vg und danke

**Comment by schinken** [comment]
Keine Ahnung, kenne ESPEasy nicht

**Comment by EpicLPer** [comment]
Du könntest ESPHome verwenden, da hat jemand eine Unterstützung für die Dostman CO2 Meter gebaut :)
Ich werd eventuell auch bald umsteigen weil der ESP mit diesem Projekt leider viel zu heiß wird und die Temp Werte durcheinander bringt.

**Comment by schinken** [comment]
@EpicLPer Das mit der Temperatur ist doch nur, wenn du ihn ins Gehäuse baust, oder? Warum soll der mit ESPHome weniger warm werden? Hast du ne Theorie?

Aber ESPHome mit Dostmann Plugin klingt btw nice. Hatte gerade überlegt ob das nicht sogar mehr sinn macht, als n eigenständiges Projekt :)

**Comment by fireball79** [comment]
Hi, auf was willst du denn umsteigen? Anderes CO2 Messgerät oder andere HW als Ersatz für den ESP?
Ich habe das Gerät aktuell über USB am Raspberry, aber ich möchte den RPI aus dem Wohnzimmer haben und den TFA irgendwo im Haus platzieren können.

Das mit der Hitze habe ich schon gelesen, aber da kann man hier schauen:
https://foosel.net/blog/2022-01-03-tfa-dostmann-meets-esphome
Die Userin hat ein andere Rückseite konstruiert, mit der das Temperaturproblem gelöst ist.

ESPHome nutzt sie auch, ich wollte nur [ESPEasy ](https://www.letscontrolit.com/wiki/index.php/ESPEasy) nutzen, weil ich damit schon viel realsiert habe. Ist quasi das gleiche wie ESPHome, nur nicht so HA lastig. Tasmota wäre auch noch ok, aber auch da gibts keine Unterstüzung.
Am Ende ist es ja eine reine Geschmacksfrage, weil ich in FHEM ja alles einbinden kann.
Und der Code hier ja auf ein MQTT schreiben kann.
VG

**Comment by EpicLPer** [comment]
> Das mit der Hitze habe ich schon gelesen, aber da kann man hier schauen: https://foosel.net/blog/2022-01-03-tfa-dostmann-meets-esphome Die Userin hat ein andere Rückseite konstruiert, mit der das Temperaturproblem gelöst ist.

In dem Blog Artikel wurde ich erwähnt, ja :) Kenne ich, ich habe die Version 1 der Rückseite mit ESP-Fach entworfen und gemacht, aber das Problem war dass dieser die Innenseite ziemlich geheizt hat.  
Foosel hat dann eine neue Rückseite entworfen, aber das Problem ist hier auch das gleiche leider, und darauf ist sie auch erst später gekommen.

@schinken Ich glaube das Problem ist dass der ESP zu viele Cycles benutzt, und sich dadurch immens erhitzt. Ich kenne mich aber leider viel zu wenig aus mit dem ganzen um hier genaueres zu sagen, aber das wäre zumindest etwas was ich in der Konversation mit Foosel rausgelesen hätte.

**Comment by schinken** [comment]
Ich hab mal gehört, dass man in loop() bissl sleepen soll um strom zu sparen. vllt würde das helfen. aber esphome mit dem plugin gefällt mir gerade sehr gut :D bin gewillt das sogar zu replacen bei mir :D

**Comment by fireball79** [comment]
Ich kann leider nicht zu beisteuern als einen TFA und nen WEMOS D1 zum testen... aber ich habe großes Interesse.
Ich habe ne [Diskussion ](https://github.com/arendst/Tasmota/discussions/14539)bei TASMOTA angestoßen, aber da kommen ähnlich Fragen auf und außerdem auch sehr technische, quasi wie oft der Sensor sendet (clock) und das das Ganze halt non-blocking läuft...

Aber bezüglich Hitze, reicht es nicht, dass man quasi pro Minute einmal die Werte ausliest und danach legt der sich wieder schlafen? Ich meine der CO2 Wert / Temp Wert wird ja nicht extrem hin die Höhe springen...

**Comment by fireball79** [comment]
Hi, für euch als kleines Update...  ich habe jetzt ESPHome mit dem Co2Mini kombiniert. Läuft super und sendet die Daten per MQTT and FHEM.
- Ich musste allerdings noch einen Pin auf dem Board anlöten. (5Volt+)
- Dann ESPHOME auf Windows installiert, ne YML erstellt und die Konfig vorgenommen und geflashed
- Dann die Verbindungen wie bei Fossel hergestellt https://foosel.net/blog/2022-01-03-tfa-dostmann-meets-esphome/
- In FHEM wurde automatisch ein MQTT Device erstellt und ich kann die Daten da sehen. 
- Am Ende noch ein bisl schick gemacht.

[co2sensor_bsp.yml.txt](https://github.com/schinken/esp8266-co2monitor/files/10677484/co2sensor_bsp.yml.txt)

Super einfach am Ende.
Die Config.yml kann man noch strippen, aber ich finde ein Fallback-WLAN und eine kleine Oberfläche zum direkt draufschauen auch ganz nice...
VG

**Comment by schinken** [comment]
Top! Vielen Dank für die Info!

**Comment by Chellux** [comment]
hi

bekomm leider beim compilieren immer diese meldung... 

> C:\Users\maik-\Downloads\esp8266-co2monitor-master(1)\esp8266-co2monitor-master\esp8266-co2monitor\esp8266-co2monitor.ino:6:10: fatal error: dep/pubsubclient-2.7/src/PubSubClient.cpp: No such file or directory
>     6 | #include "dep/pubsubclient-2.7/src/PubSubClient.cpp"
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> 
> exit status 1
> 
> Compilation error: dep/pubsubclient-2.7/src/PubSubClient.cpp: No such file or directory



was kann ich dagegen tun?

**Comment by schinken** [comment]
PubSubClient installieren?
