### ISSUE TITLE
ISR not in IRAM issue with lastest esp8266 library 

### ISSUE THREAD

**Issue by juppp** [b4ckspace/esp8266-co2monitor#2]
Hi Schinken,
with the latest version of the esp8266 library (Version 2.6.3) I could not get your example to run. 
(checked with 2.4.2 -> works fine) 
![image](https://user-images.githubusercontent.com/43467371/74725242-dba92700-523d-11ea-9c56-9d9cd9ddce21.png)

The serial output looked as following:
```
10:40:10.416 -> Hello
10:40:10.416 -> ISR not in IRAM!
10:40:10.416 -> 
10:40:10.416 -> User exception (panic/abort/assert)
10:40:10.416 -> Abort called
10:40:10.416 -> 
10:40:10.416 -> >>>stack>>>
10:40:10.416 -> 
10:40:10.416 -> ctx: cont
10:40:10.416 -> SchnippSchnapp
10:40:10.517 -> v3d128e5c
10:40:10.517 -> ~ld
```
The **ISR not in IRAM** error is generated because the `void onClock() {} ` used for the `attachInterrupt(PIN_CLK, onClock, RISING);`  does not have the `ICACHE_RAM_ATTR` attribute. This seems to be necessary now when using the esp8266 lib.

Fix: `ICACHE_RAM_ATTR void onClock() {...}`

More questions:
 I do not know if the `bool decodeDataPackage(byte data[5]) ` also needs the attribute.

Some articles about this pattern and why use the attribute:
https://randomnerdtutorials.com/interrupts-timers-esp8266-arduino-ide-nodemcu/
https://stackoverflow.com/a/58131720

**Comment by schinken** [comment]
Öhhhmmmm can you send a pull request for that? Happy to merge ;)

**Comment by schinken** [comment]
Thank you very much!

**Comment by sp9auv** [comment]
Problem with ISR not IRAM in a WEMOS or ARDUION is that memory for that handle ISR interrupt must be reserved in a section DECLARATION for values in this way for example
void ICACHE_RAM_ATTR ServiceLimitSwitchUpperShield_12_D6();
// There are solved for ATTACHINTERRUPT - you must declare this before function SETUP (very important )
In a section SETUP you can define
attachInterrupt(digitalPinToInterrupt(12), ServiceLimitSwitchUpperShield_12_D6 , FALLING );

The method ServiceLimitSwitchUpperShield_12_D6 define for example
[[ichache_IRAM_ATTR]]
void ServiceLimitSwitchUpperShield_12_D6()

Take attention what memory is need for your souce code . This value give compilator.With abouve 32 KB may also occur problem . Choice MMU from Tools
as 32 KB cache + 32 KB IRAM (balanced ). You can try other option
de sp9auv
